title: Xian   # your title
author: Xian # your name
description: Just have some fun here # your description
avatar: /images/avatar.png # change avatar

# Build Settings
markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  permalink: '/page:num/'
  per_page: 5

# Comments
# disqus:
#   shortname: xxxx-xxxxx-xxx   # your disqus shortname

# Google Analytics
# google_analytics: xx-xxxxxxxx-1  # your google analytics
